# Generated by Django 5.0.6 on 2024-06-27 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_imagen_alter_usuario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_categoriaProducto', models.AutoField(db_column='idCategoriaProducto', primary_key=True, serialize=False)),
                ('categoriaProducto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('descripcion_producto', models.CharField(max_length=300)),
                ('precio_producto', models.CharField(max_length=200)),
                ('imagen_producto', models.ImageField(upload_to='fotos/')),
                ('id_categoriaProducto', models.ForeignKey(db_column='idCategoriaProducto', on_delete=django.db.models.deletion.CASCADE, to='usuario.categoriaproducto')),
            ],
        ),
    ]
