# Generated by Django 5.0.6 on 2024-07-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_categoriaproducto_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='id_categoriaProducto',
            new_name='categoria_Producto',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_producto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
