# Generated by Django 5.0.6 on 2024-07-01 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_rename_id_categoriaproducto_producto_categoria_producto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria_Producto',
            new_name='categoriaProducto',
        ),
    ]
